---
- name: "Ubuntu-nginx-site from Git"
  become: yes
  hosts: ubuntu
  tasks:
    - name: "Installing Nginx and php8.1-fpm"
      apt:
        name: 
          - nginx
          - git 
          - php8.1-fpm
          - php8.1
        state: present
        update_cache: yes
      notify:
        - restart/enable-nginx-php8.1-fpm
        
        
        
      
  handlers:
    - name: "restart/enable-nginx-php8.1-fpm"
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - nginx
        - php8.1-fpm  
